# gitlab image
nameOverride: ""
fullnameOverride: ""
namespace: "gitlab"

gitlabimage: "gitlab/gitlab-ce"

nfs:
  name: "nfs"
  datasize: "5Gi"
  logsize: "10Gi"
  configsize: "1Gi"
  ip: "192.168.219.156"